### ISSUE TITLE
Create a branch that has no dependency on Redis

### ISSUE THREAD

**Issue by mrft** [katholiek-onderwijs-vlaanderen/sri4node#105]
Redis implmentation is incomplete (flush is cached too many times + entire redis cache is flushed, so something else, like nodejs oauth valve also using redis will lose its entire cache).

So currently Redis doesn't bring many benefits or speed improvements.

Remove redis, and check if performance is still acceptable. If so, we'll leave it disabled for now.

**Comment by jgovaerts** [comment]
In 2.0 caching is removed and so is redis.
