### ISSUE TITLE
Schema validation is not working

### ISSUE THREAD

**Issue by matthiassnellings** [katholiek-onderwijs-vlaanderen/sri4node#114]
I was able to insert wrong values in the api:
{"key":"b8cdb292-5143-41af-8daf-f11c692ec775","organisationalunit":{"href":"/organisationalunits/5673f8ba-0b04-466b-b777-9beca3d0e361"},"type":"MAIL","value":{"city":"Oostkamp","street":"/commons/streets/46798","country":"be","subCity":"Oostkamp","zipCode":"8020","$$position":{"latitude":51.156555,"longitude":3.2249694},"streetHref":"/streets/46798","countryHref":"/commons/countries/be","houseNumber":"2","subCityHref":"/subcities/58f001a8-aab5-11e3-8a7a-00ff1044a308"},"$$meta":{"permalink":"/organisationalunits/contactdetails/b8cdb292-5143-41af-8daf-f11c692ec775","created":"2017-06-02T13:14:18.773Z","modified":"2017-06-02T13:14:18.773Z"}}

while the schema is:
{"$schema":"http://json-schema.org/schema#","title":"A contactdetail contains 1 single communication channel to the organisation.","properties":{"key":{"type":"string","pattern":"^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"},"organisationalunit":{"type":"object","properties":{"href":{"type":"string","pattern":"^/organisationalunits/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"}},"required":["href"]},"priority":{"type":"integer","exclusiveMinumum":0,"description":"A positive integer that defines the order if mutliple contact-details of the same type."},"oneOf":[{"type":{"enum":["MAIL"]},"value":{"type":"object","properties":{"street":{"type":"string"},"houseNumber":{"type":"string"},"mailboxNumber":{"type":"string"},"zipCode":{"type":"string"},"city":{"type":"string"},"subCity":{"type":"string"},"country":{"type":"string"},"streetHref":{"type":"string","pattern":"^/streets/[0-9]*$"},"subCityHref":{"type":"string","pattern":"^/subcities/[0-9]*$"},"countryHref":{"type":"string","pattern":"^/countries/[a-f]{2}$"}},"required":["street","houseNumber","zipCode","city","country","countryHref"]}},{"type":{"enum":["EMAIL"]},"value":{"type":"string","format":{"type":"string","format":"email","minLength":1,"maxLength":254,"description":"An email address of this organisation."}}},{"type":{"enum":["PHONE","FAX"]},"value":{"type":"string","oneOf":[{"pattern":"^0[15-8][0-9] [0-9]{2} [0-9]{2} [0-9]{2}$"},{"pattern":"^0[2-3] [0-9]{3} [0-9]{2} [0-9]{2}$"},{"pattern":"^0[49] [23][0-9]{2} [0-9]{2} [0-9]{2}$"},{"pattern":"^04[0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2}$"},{"pattern":"^[+][0-9]{7}[0-9]{0,8}$"}]}},{"type":{"enum":["WEBSITE"]},"value":{"type":"string","format":{"type":"string","minLength":1,"maxLength":2000,"format":"uri","description":"A website of this organisation."}}}]},"required":["key","organisationalunit","type","value"]}

**Comment by jgovaerts** [comment]
Not reproducible in v2.0
