### ISSUE TITLE
If a property is missing, it is not set to null

### ISSUE THREAD

**Issue by matthiassnellings** [katholiek-onderwijs-vlaanderen/sri4node#118]
Ik heb net gemerkt dat als ik een veld niet terugstuur (met de bedoeling om het op null te zetten, meer bepaald met een einddatum), dan wordt dat gewoon genegeerd, de oude waarde blijft dus gewoon staan.

null sturen werkt wel (maar dan zou je wel expliciet in het schema null moeten toelaten)

Maar beiden zouden moeten werken

**Comment by jgovaerts** [comment]
In v2.0 missing fields and explicit null are treated similar: considered as missing during validation and set to null in the database.
