### ISSUE TITLE
parameter values containing a '

### ISSUE THREAD

**Issue by matthiassnellings** [katholiek-onderwijs-vlaanderen/sri4node#119]
http://samenscholing-api-acc.eu-central-1.elasticbeanstalk.com/commons/subcities?nameContains=Sint-Job-in-%27t-Goor
does not work
but
http://samenscholing-api-acc.eu-central-1.elasticbeanstalk.com/commons/subcities?nameContains=Sint-Job-in-%27%27t-Goor
does work

I have to 'sql-escape' the character myself but this should not be done on the client

**Comment by feelitloveit** [comment]
You are right. defaultFilter.js is not using `.param()` but just including the string. Kind of dangerous actually!
