### ISSUE TITLE
For PUT: Check if the value of the key in the body is the same as the key in the url path

### ISSUE THREAD

**Issue by matthiassnellings** [katholiek-onderwijs-vlaanderen/sri4node#127]
You can now send A PUT to /organisationalunits/relations/guidX

and in the body you send 
{
 guid Y
 ...
}

Do check if they are the same and throw error if they are not.

In Persons API I used code: "key.mismatch"

**Comment by stefanvds1** [comment]
yes, and the current error is very confusing. (something like: guid already in use)

**Comment by jgovaerts** [comment]
fixed in v2.0
