### ISSUE TITLE
When expanding on a list you don't want to add results

### ISSUE THREAD

**Issue by matthiassnellings** [katholiek-onderwijs-vlaanderen/sri4node#131]
for example:
`http://samenscholing-api-acc.eu-central-1.elasticbeanstalk.com/organisationalunits/externalidentifiers?organisationalunit=a2aeaf68-a3a4-11e3-ace8-005056872b95&expand=results.organisationalunit
`
You need to add the prefix "results."

`http://samenscholing-api-acc.eu-central-1.elasticbeanstalk.com/organisationalunits/externalidentifiers?organisationalunit=a2aeaf68-a3a4-11e3-ace8-005056872b95&expand=organisationalunit`

**Comment by jgovaerts** [comment]
same as #153
