### ISSUE TITLE
filter on version doesnt work on first run

### ISSUE THREAD

**Issue by stefanvds1** [katholiek-onderwijs-vlaanderen/sri4node#132]
when you start sri4node on a new db and try to use the filter &$$meta.version=8 for example, it says this is not a valid parameter. when you restart sri4node it now knows this does exist and all is good, but the first time, when the code adds this version param, some part of sri4node doesnt know

**Comment by jgovaerts** [comment]
not reproducible now. maybe fixed in recent changes?
