### ISSUE TITLE
sri4node.utils is null

### ISSUE THREAD

**Issue by stefanvds1** [katholiek-onderwijs-vlaanderen/sri4node#136]
the utils somehow isn't exposed anymore. trying to use addReferencingResources etc throws: 
TypeError: Cannot read property 'addReferencingResources' of null

const sri4node = require('sri4node');
const $u = sri4node.utils;

async function includeAttendees(tx, sriRequest, elements) {
  'use strict';
  var addReferencingResources = $u.addReferencingResources('/events/attendees', 'event', '$$attendees', false);

  return addReferencingResources(tx, elements);
}

**Comment by feelitloveit** [comment]
This is now `sriConfig.utils` (only after you run sri4node.configure) . But this is not handy when you want to use this inside the config itself.

**Comment by jgovaerts** [comment]
fixed in sprint-169-0
Changed global configuration in a way that sri4node.utils is now available directly after require instead of after configure of sri4node. Now both sri4node.utils and sriConfig.utils will work.
