### ISSUE TITLE
customroutes don't get hit/ran

### ISSUE THREAD

**Issue by stefanvds1** [katholiek-onderwijs-vlaanderen/sri4node#137]
in events api i have the following customroutes in the mapping

  customroutes: [
    { route: '/events/:key/ical', handler: icalify, method: 'GET' },
    { route: '/events/ical', handler: icalifylist, method: 'GET' }
  ]

the icalify function (and icalifylist) don't get hit/ran.

**Comment by jgovaerts** [comment]
customroutes are refactored to v2.0 in sprint-169-0. see docs for changed mechanism and interface.
