### ISSUE TITLE
easy support for $$meta.type

### ISSUE THREAD

**Issue by mrft** [katholiek-onderwijs-vlaanderen/sri4node#170]
Since it's always the same per resource anyway, just some config option ('type'? or metaType) should suffice, I guess...
Or is there another way to easily add default things to the $$meta section?

**Comment by mrft** [comment]
It should even be manadtory i guess (if config doesn't contain it, sri4node should refuse to start up)...

**Comment by dimitrydhondt** [comment]
Yes, because SRI mandates the $$meta.type field :)
    On Friday, February 8, 2019, 9:00:53 AM GMT+1, mrft <notifications@github.com> wrote:  
 
 
It should even be manadtory i guess (if config doesn't contain it, sri4node should refuse to start up)...

**Comment by jgovaerts** [comment]
Added in 192-0. Not (yet) mandatory, a warning is printed if metaType is missing for a resource.
