### ISSUE TITLE
PUTTING on a deleted item is flawed

### ISSUE THREAD

**Issue by mrft** [katholiek-onderwijs-vlaanderen/sri4node#197]
Observed behavior:
A put on a deleted resource returns 200 OK, but the deleted timestamp doesn't get removed. This means that the resource is probably being updated with new information, but it is not undeleted.

Expected behavior:
- The PUT should only work if the user has CREATE rights (as it's a new creation as far as the user concerns) cfr. sri4node-security-api plugin.
- The PUT should send a CREATE message to audit-broadcast cfr. sri4node-audit-broadcast-api plugin.
- After the PUT the deleted tiestamp should be removed.
- After the PUT the resource contains the info as in the PUT, not the 'logically deleted' resource as it stiil existed on the DB
- A PATCH of a deleted resource should fail !!!

**Comment by jgovaerts** [comment]
fixed in https://github.com/katholiek-onderwijs-vlaanderen/sri4node/commit/f1fb3a39fe490c4cc89a7e73089fcef639a97e8c
