### ISSUE TITLE
Functional version of cache configuration

### ISSUE THREAD

**Issue by dimitrydhondt** [katholiek-onderwijs-vlaanderen/sri4node#34]
In staying with functional programming ideas, most configuration in sri4node is done by registering a callback function. Right now the cache implementation is using a more declarative style. Is it possible to move to a function as well ? As long as we define the input & output of the caching function well, we should be able to make this pluggable.

**Comment by dimitrydhondt** [comment]
Ideally not only the cache implemetation, but also the cache strategy should be pluggable..

**Comment by rodrigouroz** [comment]
I'm not sure I understand what you mean with this.

Are you referring to the way clients configure sri4node for caching or the way the caching implementations in sri4node are done?

**Comment by dimitrydhondt** [comment]
The way it is configured.

**Comment by dimitrydhondt** [comment]
Something like : 

cache : {
  storage: redisCache, // determines the cache implementation
  strategy: lruCache    // determines the caching strategy (ttl / lru / more advanced..)
}

I'm thinking the "storage" would be an object with some methods like contains / get / put / remove
I'm also thinking a more advanced caching strategy would be a good idea. Something like : 

- store a hit-count for URLs (this portion requires some strategy to keep this storage section from growing out of control)
- then use the hit-count to determine what URLs really are hit most frequently

For example : a process that does a batch GET on ALL /persons would clear the effectiveness of the cache in a LRU type strategy, but not in this more advanced one.

etc.. etc..

In any case, having a clear modular, plugable system allows us to evolve this easily, and allows clients of sri4node to work on other caching strategies.

I'm sure we can come up with other strategies.

**Comment by rodrigouroz** [comment]
So if I understood this correctly sri4node will have some storage implementations and some strategy implementations that must be public, and the client can choose either from those or define new ones.

Something like:

```javascript
var $stor = sri4node.cacheStorages;
var $stra = sri4node.cacheStrategies;

cache: {
  storage: $stor.redisCache(ttl),
  strategy: $stor.lruCache(size)
}

// And another could be:

cache: {
   storage: $stor.localCache,
   strategy: myCustom.ownStrategy()
}
```

**Comment by dimitrydhondt** [comment]
Exactly !

**Comment by dimitrydhondt** [comment]
We also need to be able to register a secure function.

cache : {
  store : redisStore,
  evict : lfuStrategy,
  secure : $sri4node-security-api.afterread
}

**Comment by rodrigouroz** [comment]
Refactor plan: https://docs.google.com/document/d/1-g6IlvIn6A59iHcbHNW9ZmKvGTQCSqjCnaQI5GHhHEw/edit?usp=drive_web

**Comment by rodrigouroz** [comment]
Important: take into account that a GET inside a Batch request should not invalidate the cache. In the current implementation for each element in the batch the cache is invalidated because PUT is the only implemented verb in the Batch.

**Comment by rodrigouroz** [comment]
I guess this should be delayed for sri4node 2.0

**Comment by dimitrydhondt** [comment]
Yes

**Comment by mrft** [comment]
Caching has been removed, closing.
