### ISSUE TITLE
/batch operation should support GET and DELETE as well as PUT.

### ISSUE THREAD

**Issue by dimitrydhondt** [katholiek-onderwijs-vlaanderen/sri4node#56]
/batch should allow the inclusion of GET and DELETE operations.

**Comment by dimitrydhondt** [comment]
I recently realized that GET in a /batch is perhaps not such a good idea. A batch uses PUT to communicate with the server. If that invalidates caching, then it could be worse for a lot of clients (that have a client-side cache -> like browsers) ?

**Comment by rodrigouroz** [comment]
The cache invalidation should be per action and resource, not per HTTP verb. I checked the implementation and it's true, batch full of GETs will invalidate the cache. However there's a pending refactor of that middleware and I'll add a comment to that issue to remember this scenario and fix it.

**Comment by rodrigouroz** [comment]
This is so because right now PUT is the only implemented verb in the batch, so the secure cache assumes is a PUT. I've already commented on the other issue.

**Comment by dimitrydhondt** [comment]
@eznibe You'll need to add at least the DELETE operation to the batch. When deleting a curriculum with 2000 nodes you will need a batch operation :-)

**Comment by dimitrydhondt** [comment]
Does GET in a batch make sense from an HTTP point of view ? Currently /batch is defined as a PUT operation (with 1-n PUT and 1-n DELETE operations inside). If we add x GET operations, no cache-benefits will occur in the client, right ?

Unless we change the SRI spec to allow /batch GET. But only containing GET operations in the batch then... 

I believe the body of a GET operation is considered in the caching implementations (I think HTTP defines it that way).

Anyone has experience here ?

**Comment by dimitrydhondt** [comment]
Perhaps the SRI spec could exclude hybrid batches where GET/DELETE/PUT are mixed.
So only a batch of n GET operations, OR a batch of n PUT operations, OR a batch of n DELETE operations.

But that would exclude the possibility to do an atomic DELETE + PUT combination. Not so great...

**Comment by dimitrydhondt** [comment]
See the changes in the SRI spec (batch operation) : 
https://github.com/dimitrydhondt/sri#batch-operations

**Comment by dimitrydhondt** [comment]
Also implement parallel versus sequential batches.

**Comment by dimitrydhondt** [comment]
@rodrigouroz Go for the GET and DELETE implementation in batches for now.
The parallel versus sequential is still under debate.

**Comment by dimitrydhondt** [comment]
Also implement POST operations. For example : using /validate is described as a POST operation.

In general the BATCH is simply an envelop of multiple HTTP operations, where all of them are executed in the same transaction.

**Comment by jgovaerts** [comment]
In the 2.0 refactor batch supports all 'normal' operations (so batch in batch is not impelemented).
