### ISSUE TITLE
Refactor batch process to call after functions once for the whole batch

### ISSUE THREAD

**Issue by rodrigouroz** [katholiek-onderwijs-vlaanderen/sri4node#86]
Right now is using the `executePutInsideTransaction` method that calls the `postProcess` method for each batch element, when the `postProcess` method is prepared to receive a set of elements.

This will improve performance significantly for batch updates.

**Comment by rodrigouroz** [comment]
This is no longer easy with the current structure of 1.2, it should be addressed in new refactor 2.0
The problem is that now the batch operations will support any action (GET, PUT and DELETE) and then it's hard to split the execution and the postprocess of the after* functions.

**Comment by mrft** [comment]
REJECTED
