### ISSUE TITLE
Structure the codebase better

### ISSUE THREAD

**Issue by dimitrydhondt** [katholiek-onderwijs-vlaanderen/sri4node#95]
Please structure the codebase in a better way, because right now it is a bit all over the place. Especially sri4node.js is too large to comprehend.

A good, compact documentation of the overal structure of the code would also help. Like with an explanation on how the secure cache is integrated.

I was trying to analyze the batch processing to see if I could quickly add support for GET operation, but I gave up - too complex now...

**Comment by rodrigouroz** [comment]
@dimitrydhondt: Does this go to 2.0 or do we do something in version 1?

**Comment by dimitrydhondt** [comment]
Goes into 2.0

    On Thursday, May 12, 2016 12:40 PM, Rodrigo Uroz <notifications@github.com> wrote:
 

 @dimitrydhondt: Does this go to 2.0 or do we do something in version 1?—

**Comment by jgovaerts** [comment]
Done in 2.0 refactor.
